classes/helpers/Permissions.php, classes/models/Converters.php
Cleans up backend after https://github.com/aula-app/aula-frontend/issues/622 is deployed.
=> fix: remove db export and csv export

CHANGELOG.md, classes/models/Idea.php
Fix issue https://github.com/aula-app/aula-frontend/issues/601
=> Fix number of users in a room with voting rights

classes/models/User.php
Fix https://github.com/aula-app/aula-frontend/issues/627
=> Add roles column back to getUsers response

classes/helpers/Permissions.php
Fix https://github.com/aula-app/aula-frontend/issues/643
=> Add permission to admins to User->setUserDisplayname

.github/workflows/prod.yml
=> feat: add prod env to workflows

controllers/upload.php
=> fix: check code header regex

controllers/upload.php
=> Release staging->prod

controllers/login.php
=> fix cors response when there is no instance code in the request

controllers/login.php, controllers/upload.php
=> fix cors in login.php

classes/models/Database.php, classes/models/User.php
* fix: addUser or addUserCSV - fix checking for existing email/username
* feat: editUser - check if (any or both) new email/username belong to another user
=> feat: editUser - check for existing new email/username

src/classes/models/Room.php
Fix delete room response: Undefined variable $rowCount
=> Fix delete room  warning

CHANGELOG.md, src/classes/helpers/Permissions.php, src/classes/helpers/ResponseBuilder.php, src/classes/models/Database.php, src/classes/models/User.php, src/classes/repositories/README.md, src/classes/repositories/RoomRepository.php
Implements CSV import to multiple Rooms. Resolves duplicate Users.
=> fix(csv): import users to multiple rooms

Dockerfile, cron.php, crontab, docker-entrypoint.sh, src/classes/scheduler/CommandDispatcher.php, src/classes/usecases/commands/InstanceOnlineModeHandler.php, src/classes/usecases/commands/SendEmailHandler.php
Adds crontab and starts cron service in the BE container.
=> fix(cron): running cron inside docker container

src/classes/scheduler/CommandScheduler.php
=> fix(commands): exception in one instance can stop processing others

src/classes/models/User.php
Alternative implementation to https://github.com/aula-app/aula-frontend/issues/439
When CSV has at least one entry that has no username, email, displayname or realname, we cancel the whole operation (adding of any user from CSV is not performed), and return an error.
For example, both of these rows would break the CSV import:
```csv
realname;displayname;username;email;about_me
;;;INVALID_EMAIL;whatever 3
;;;;whatever 8
```
Otherwise, this test CSV:
```csv
realname;displayname;username;email;about_me
First1 Last1;First Last 1;;user_1@example.com;whatever 1
First2 Last2;First Last 2;;INVALID_EMAIL;whatever 2
First1 Last4;First Last 4;;;whatever 4
;FirstLast55555555;;;whatever 5
First1 Last6;;;;whatever 6
First1Last7777777777;;;;whatever 7
```
produces this response
```json
{
"success": …
```
=> fix(csv): username empty

.github/workflows/main.yml
=> fix: github workflow permissions

src/classes/models/Idea.php
=> ref(idea): ref available votes for clarity

config/base_config.php-example, config/instances_config.php-example, src/classes/helpers/InstanceConfig.php, src/classes/models/Database.php, src/classes/scheduler/CommandScheduler.php, src/controllers/auth0.php, src/controllers/change_password.php, src/controllers/forgot_password.php, src/controllers/get_necessary_consents.php, src/controllers/give_consent.php, src/controllers/instance.php, src/controllers/login.php, src/controllers/model.php, src/controllers/refresh_token.php, src/controllers/set_password.php, src/controllers/upload.php, src/controllers/user_consent.php
https://github.com/aula-app/aula-backend/issues/294
=> fix: instance code checks

CHANGELOG.md, src/controllers/user_consent.php
=> fix: instance config refactor

config/base_config.php-example, src/controllers/instance.php
this will fix failing OPTIONS requests (ios)
=> fix: included script should exit when writing http response

src/classes/models/User.php
Fix bug where editUSer update query was not being run.
=> Fix editUser to do the DB query
